version: '3'

services:
  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - "5432:5432"
    
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
  
  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    ports:
      - "80:80"