# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-25 16:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctype', models.CharField(choices=[('client', 'Client'), ('kitchen', 'Kitchen')], max_length=10)),
                ('order', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('new', 'New'), ('rendered', 'Rendered'), ('printed', 'Printed')], max_length=10)),
                ('pdf_file', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100, unique=True)),
                ('check_type', models.CharField(choices=[('client', 'Client'), ('kitchen', 'Kitchen')], max_length=10)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='printer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.Printer'),
        ),
    ]
